apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: observability-bookinfo-west-cluster
  namespace: argocd
spec:
  destination:
    namespace: bookinfo
    server: https://west-cluster.aws.scratch.caas.tetrate.com:443
  project: default
  source:
    directory:
      include: "{app-bookinfo-west-cluster.yaml}"
    path: demos/observability/artifacts
    repoURL: https://github.com/tetratecx/tetrate-platform-ntt
    targetRevision: HEAD
  syncPolicy:
    automated:
      enabled: true
    syncOptions:
    - CreateNamespace=true
    - AllowSharedResource=true
    - IgnoreInClusterResources=true
    - PruneLast=true