apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: observability-bookinfo-corp-edge
  namespace: argocd
spec:
  destination:
    namespace: bookinfo
    server: https://corp-edge.aws.scratch.caas.tetrate.com:443
  project: default
  source:
    directory:
      include: "{app-bookinfo-corp-edge.yaml}"
    path: demos/observability/artifacts
    repoURL: https://github.com/tetratecx/tetrate-platform-ntt
    targetRevision: HEAD
  syncPolicy:
    automated:
      enabled: true
    syncOptions:
    - CreateNamespace=true