version: "3"

tasks:
  default:
    desc: "Show all available tasks"
    cmds:
      - task --list

  generate-traffic:
    desc: "Traffic generator to transactions.dynabank.com"
    silent: true
    cmds:
      - echo "Generating traffic to transactions.dynabank.com..."
      - bash ./generate-traffic.sh
