apiVersion: v1
kind: Namespace
metadata:
  labels:
    kubernetes.io/metadata.name: transaction-service
    istio-injection: enabled
    tetrate.io/rev: default
  name: transaction-service
---
##################################################################################################
# Fraud Detection Service
##################################################################################################
apiVersion: v1
kind: Service
metadata:
  name: fraud-detection
  namespace: transaction-service
  labels:
    app: fraud-detection
    service: fraud-detection
    traffic.tetrate.io/global: "true"
spec:
  ports:
  - port: 9080
    name: http
  selector:
    app: fraud-detection
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: transaction-fraud-detection
  namespace: transaction-service
  labels:
    account: fraud-detection
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fraud-detection-v2
  namespace: transaction-service
  labels:
    app: fraud-detection
    version: v2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fraud-detection
      version: v2
  template:
    metadata:
      labels:
        app: fraud-detection
        version: v2
    spec:
      serviceAccountName: transaction-fraud-detection
      containers:
      - name: fraud-detection
        image: us-east1-docker.pkg.dev/dogfood-cx/registryrepository/giraffe:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 9080
        env:
        - name: SERVICE_NAME
          value: "fraud-detection"
        - name: SERVICE_VERSION
          value: "v2"
        - name: SERVICE_PORT
          value: "9080"
        - name: UPSTREAM_URLS
          value: "http://risk-assessment:9080"
        - name: UPSTREAM_PATH
          value: "/risk-assessment"
        - name: OTEL_EXPORTER_OTLP_ENDPOINT
          value: "otel-collector:4317"
        - name: RESPONSE_FIELD_FRAUD_MODEL
          value: "ml_v2"
        - name: RESPONSE_FIELD_ENHANCED_ANALYSIS
          value: "true"
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
---
##################################################################################################
# Risk Assessment Service
##################################################################################################
apiVersion: v1
kind: Service
metadata:
  name: risk-assessment
  namespace: transaction-service
  labels:
    app: risk-assessment
    service: risk-assessment
    traffic.tetrate.io/global: "true"
spec:
  ports:
  - port: 9080
    name: http
  selector:
    app: risk-assessment
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: transaction-risk-assessment
  namespace: transaction-service
  labels:
    account: risk-assessment
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: risk-assessment-v1
  namespace: transaction-service
  labels:
    app: risk-assessment
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: risk-assessment
      version: v1
  template:
    metadata:
      labels:
        app: risk-assessment
        version: v1
    spec:
      serviceAccountName: transaction-risk-assessment
      containers:
      - name: risk-assessment
        image: us-east1-docker.pkg.dev/dogfood-cx/registryrepository/giraffe:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 9080
        env:
        - name: SERVICE_NAME
          value: "risk-assessment"
        - name: SERVICE_VERSION
          value: "v1"
        - name: SERVICE_PORT
          value: "9080"
        - name: OTEL_EXPORTER_OTLP_ENDPOINT
          value: "otel-collector:4317"
        - name: CALL_UPSTREAMS
          value: "false"
        - name: RESPONSE_TEMPLATE
          value: '{"service":"risk-assessment","transaction_id":"txn-001","risk_score":75,"risk_level":"medium","factors":["unusual_amount","new_merchant"],"recommendation":"manual_review"}'
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName