apiVersion: v1
kind: Service
metadata:
  name: account-service
  labels:
    app: account-service
spec:
  ports:
    - port: 9080
      name: http
  selector:
    app: account-service
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: transaction-account-service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: account-service-v1
  labels:
    app: account-service
    version: v1
spec:
  replicas: {{ .Values.accountService.replicas.v1 }}
  selector:
    matchLabels:
      app: account-service
      version: v1
  template:
    metadata:
      labels:
        app: account-service
        version: v1
    spec:
      serviceAccountName: transaction-account-service
      containers:
        - name: account-service
          image: "{{ .Values.global.image.repository }}:{{ .Values.global.image.tag }}"
          imagePullPolicy: Always
          ports:
            - containerPort: 9080
          env:
            - name: SERVICE_NAME
              value: "account-service"
            - name: SERVICE_VERSION
              value: "v1"
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: "{{ .Values.global.otelCollectorEndpoint }}"
            - name: SERVICE_PORT
              value: "9080"
            - name: CALL_UPSTREAMS
              value: "false"
            - name: RESPONSE_TEMPLATE
              value: '{"service":"account-service","account_id":"12345","account_type":"checking","balance":1500.00,"status":"active","last_activity":"2024-01-01T10:00:00Z"}'
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace