---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  name: corp-app-resilience
  namespace: argocd
  annotations:
    argocd.argoproj.io/display-name: "corp-app-resilience"
spec:
  project: default
  syncPolicy:
    automated:
      prune: true
    syncOptions:
    - CreateNamespace=true
    - AllowSharedResource=true
    - IgnoreInClusterResources=true
    - PruneLast=true
  destination:
    namespace: tetrate-system
    server: https://kubernetes.default.svc
  source:
    directory:
      recurse: true
      include: "{online-banking-secret.yaml,http-profile.yaml,tenant-settings.yaml}"
    path: demos/app-resilience/artifacts
    repoURL: https://github.com/tetratecx/tetrate-platform-ntt.git