version: "3"

tasks:
  default:
    desc: "Show all available tasks"
    cmds:
      - task --list

  app-onboarding:
    desc: "Onboarding Transaction Portal Application"
    silent: true
    cmds:
      - echo "Onboarding Transaction Portal Application. Takes a few seconds..."
      - kubectl create namespace transaction-oversight
      - kubectl label namespace transaction-oversight istio-injection=enabled
      - helm upgrade --install transaction-portal ../helm/app --namespace transaction-oversight
      - kubectl apply -f artifacts/tsb-resources.yaml

  expose-app:
    desc: "Transaction Portal Application Exposure"
    silent: true
    cmds:
      - echo "Transaction Portal application exposure through online-banking.dynabank.com..."
      - kubectl apply -f artifacts/gw-config.yaml

  generate-traffic-443:
    desc: "Traffic generator to online-banking.dynabank.com:443"
    silent: true
    cmds:
      - echo "Generating traffic to online-banking.dynabank.com:443..."
      - bash artifacts/generate-traffic-443.sh
  
  clean-up:
    desc: "Deletion of all demo's resources"
    silent: true
    cmds:
      - echo "Deletion of all demo's resources..."
      - helm uninstall transaction-portal --namespace transaction-oversight
      - kubectl delete namespace transaction-oversight
      - kubectl delete -f artifacts/tsb-resources.yaml --ignore-not-found
      - kubectl delete -f artifacts/gw-config.yaml --ignore-not-found



