apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: business-continuity-app
  namespace: argocd
spec:
  generators:
    - matrix:
        generators:
        - clusters:
            selector:
              matchLabels:
                tsb: t2
        - list:
            elements:
              - appName: transaction-portal
                demo: business-continuity
  template:
    metadata:
      name: '{{name}}-{{appName}}'
    spec:
      project: default
      sources:
      - repoURL: https://github.com/tetratecx/tetrate-platform-ntt.git
        path: demos/helm/app
        targetRevision: HEAD
        helm:
          valueFiles:
            - '$values/demos/{{demo}}/app/values.yaml'
      - repoURL: https://github.com/tetratecx/tetrate-platform-ntt.git
        path: .
        targetRevision: HEAD
        ref: values         
      destination:
        name: '{{name}}'
        namespace: '{{demo}}'
      syncPolicy:
        managedNamespaceMetadata:
          labels: 
            istio.io/rev: default
        automated:
          prune: true
          selfHeal: true
        syncOptions:
        - CreateNamespace=true