apiVersion: v1
kind: Namespace
metadata:
  labels:
    kubernetes.io/metadata.name: transaction-service
    istio-injection: enabled
    tetrate.io/rev: default
  name: transaction-service
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    gateway.tetrate.io/expose: "global"
    gateway.tetrate.io/edge-clusters: "corp-edge"
    gateway.tetrate.io/host: "online-banking.dynabank.com"
    gateway.tetrate.io/protocol: "HTTPS"
    gateway.tetrate.io/tls-secret: "online-banking-certs"
    gateway.tetrate.io/cloud-annotations: |
      service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
      service.beta.kubernetes.io/aws-load-balancer-scheme: "internet-facing"
  name: web-portal
  namespace: transaction-service
  labels:
    app: web-portal
    service: web-portal
spec:
  type: ClusterIP
  selector:
    app: web-portal
  ports:
    - name: http
      port: 3000
      targetPort: http
      protocol: TCP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-portal
  namespace: transaction-service
  labels:
    app: web-portal
    service: web-portal
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-portal
  template:
    metadata:
      labels:
        app: web-portal
        service: web-portal
        version: v1
    spec:
      containers:
        - name: web-portal
          image: us-east1-docker.pkg.dev/dogfood-cx/registryrepository/dynabank/web-portal:latest
          imagePullPolicy: Always
          env:
            - name: PORT
              value: "3000"
            - name: REACT_APP_API_URL
              value: "http://transaction-api:3000"
            - name: REACT_APP_ENVIRONMENT
              value: "development"
          ports:
            - containerPort: 3000
              name: http
          livenessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 10
            periodSeconds: 5
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 200m
              memory: 128Mi
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            runAsUser: 1000
          volumeMounts:
            - name: tmp-volume
              mountPath: /tmp
      volumes:
        - name: tmp-volume
          emptyDir: {}